name: Build App installers (Mac & Windows)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build_mac:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Build Mac App (.dmg)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:mac -- -p never -c.mac.identity=null
      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mac-Installer
          path: dist/*.dmg

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Build Windows App (.exe)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:win -- -p never
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Installer
          path: dist/*.exe
